### ISSUE TITLE
TODO from 2020-02-22

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/typesetting#12]
- [x] Decision Form on Typesetting Review - @ajrbyers 

- [x] Move the Files for Typesetting block to a Modal - @mauromsl 
- [x] Add other standard Modals - @mauromsl 

- [x] Add a complete typesetting button - @mauromsl 

- [x] Manage rounds as per https://github.com/BirkbeckCTP/typesetting/issues/2 - @mauromsl 

- [x] Proofreader Interface https://github.com/BirkbeckCTP/typesetting/issues/5 - @ajrbyers 

- [x] Add Select All JS to Edit Assignment block - @ajrbyers

**Comment by mauromsl** [comment]
47e69c694d4a7614082268479a8a0395b4b8cca9

**Comment by ajrbyers** [comment]
0852c4aac346d79f1efd857dd4b3b3743996e607

**Comment by ajrbyers** [comment]
select all js: eabbc0104c9a5d84dd4e6e3f1ecf31f607215860
